[package]
name = "uda_registry_test"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[scripts]
test = "snforge test"

[dependencies]
starknet = "2.12.0"

[dev-dependencies]
cairo_test = "2.12.0"
snforge_std = "0.48.1"
assert_macros = "2.12.0"


[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]


[[target.starknet-contract]] # allows to build the package as a starknet contract
sierra = true
casm = true
