[package]
name = "uda_registry_test"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.9.2"

[dev-dependencies]
cairo_test = "2.11.4"

[[target.starknet-contract]] # allows to build the package as a starknet contract
sierra = true
casm = true
